name: Apply Terraform To Main

on:
  push:
    branches:
      - main

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      BUCKET: terraform-state-bucket-227609615604
      TF_VAR_gcp_location: europe-west1
      GCP_PROJECT_ID: dda-and-fpp
      TFVARS_FILE: main.tfvars
      WORKSPACE_NAME: default

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.TERRAFORM_SA }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config="bucket=${{ env.BUCKET }}" -backend-config="prefix=terraform/${{ env.WORKSPACE_NAME }}/state"
        working-directory: infra
        env:
          TF_VAR_project: ${{ env.GCP_PROJECT_ID }}

      - name: Select or Create Workspace
        run: terraform workspace select ${{ env.WORKSPACE_NAME }} || terraform workspace new ${{ env.WORKSPACE_NAME }}
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="${{ env.TFVARS_FILE }}"
        working-directory: infra
        env:
          TF_VAR_project: ${{ env.GCP_PROJECT_ID }}